In [24]:
import os
import operator
import sys
import random
import math
import re
import time
import numpy as np
import skimage.io
from skimage import color
import matplotlib
import matplotlib.pyplot as plt
import tensorflow as tf
import matplotlib.patches as patches
from IPython.display import SVG
from keras.utils.vis_utils import model_to_dot
from svglib.svglib import svg2rlg
from reportlab.graphics import renderPDF



# Root directory of the project

ROOT_DIR = os.path.abspath("/srv/home/whao/NextGen/new_debug/run/run1/")


# Import Mask RCNN
sys.path.append(ROOT_DIR)  # To find local version of the library
from mrcnn import utils
from mrcnn import visualize
from mrcnn.visualize import display_images
import mrcnn.model as modellib
from mrcnn.model import log
from samples.balloon import balloon

%matplotlib inline 


# Directory to save logs and trained model

MODEL_DIR = os.path.join(ROOT_DIR, "logs")


# Path to Ballon trained weights

# You can download this file from the Releases page

# https://github.com/matterport/Mask_RCNN/releases

BALLOON_WEIGHTS_PATH = "/srv/home/whao/NextGen/new_debug/run/run1/logs/balloon20180728T0017/mask_rcnn_balloon_0010.h5"  # TODO: update this path


# Directory of images to run detection on

#IMAGE_DIR = os.path.join(ROOT_DIR, "testimages/val")
IMAGE_DIR = "/srv/home/whao/NextGen/new_debug/run/run1/datasets/dataprep/datasets/Loop_detection/val/"

In [6]:
config = balloon.BalloonConfig()
for n in range(9, 0, -1):
    print('#################################################################################')
    print('DETECTION_MIN_CONFIDENCE'+ ':' + str(n/10))

    # Override the training configurations with a few

    # changes for inferencing.

    class InferenceConfig(config.__class__):
        # Run detection on one image at a time
        GPU_COUNT = 1
        IMAGES_PER_GPU = 1
        DETECTION_MIN_CONFIDENCE = n/10

    config = InferenceConfig()
    model = modellib.MaskRCNN(mode="inference", model_dir=MODEL_DIR, config=config)
    model.load_weights(BALLOON_WEIGHTS_PATH , by_name=True)
    class_names = ['BG', 'Loop111']
    files = os.listdir(IMAGE_DIR)
    path = ROOT_DIR + "/samples/" + 'generated' + str(n)
    if not os.path.exists(path):
        os.makedirs(path)
        
    for i in range(len(files)): 

        if files[i] == ".DS_Store":

            continue

        print(files[i])

        line = files[i]

        image = skimage.io.imread(os.path.join(IMAGE_DIR, files[i]))
        image_rgb = color.gray2rgb(image) 

        # Run detection

        results = model.detect([image_rgb], verbose=1)


        # Visualize results
        r = results[0]
        outfile = ROOT_DIR + "/samples/" + 'generated' + str(n) + '/' + line[:-4] + '.txt'
        f = open(outfile,mode = 'w+')
        list1 = r['rois']

        for j in range(len(list1)):

            f.write(str(list1[j]).replace("[","").replace("]","").lstrip(' '))

            f.write("\n")

        print(list1)

        f.close()

#################################################################################
DETECTION_MIN_CONFIDENCE:0.9
Re-starting from epoch 10
ROI1_100kx_4200CL_foil1.jpg
Processing 1 images
image                    shape: (1024, 1024, 3)       min:    3.00000  max:  255.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -120.70000  max:  151.10000  float64
image_metas              shape: (1, 14)               min:    0.00000  max: 1024.00000  int64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32
[[620 705 645 725]
 [467 155 493 182]
 [ 72 423  91 438]
 [679 923 710 958]
 [418 578 443 610]
 [215  21 246  49]]
map1_70kx.jpg
Processing 1 images
image                    shape: (1024, 1024, 3)       min:    1.00000  max:  254.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -122.70000  max:  150.10000  float64
image_metas              shape: (1, 14)               min:    0.00000  max: 1024.00000  int64
an

[[783 543 814 590]
 [262 417 288 435]
 [221 542 236 558]
 [654 544 672 562]]
ROI11_100kx_4200CL_foil1.jpg
Processing 1 images
image                    shape: (1024, 1024, 3)       min:    1.00000  max:  254.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -122.70000  max:  150.10000  float64
image_metas              shape: (1, 14)               min:    0.00000  max: 1024.00000  int64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32
[[501 301 526 343]
 [869 270 890 291]
 [566 198 581 224]
 [  3 580  29 617]
 [796 253 824 279]
 [391 110 442 173]
 [101 451 122 480]
 [606 229 633 250]
 [752 892 771 910]
 [119 918 137 936]
 [326 838 344 856]
 [872 225 894 252]]
ROI10_100kx_4200CL_foil1.jpg
Processing 1 images
image                    shape: (1024, 1024, 3)       min:    0.00000  max:  255.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  151.10000  float64
image_metas              s

[[207 630 238 683]
 [537 789 581 845]
 [934 884 952 912]
 [433 869 467 928]
 [891 272 929 341]]
map4_70kx.jpg
Processing 1 images
image                    shape: (1024, 1024, 3)       min:    0.00000  max:  252.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  148.10000  float64
image_metas              shape: (1, 14)               min:    0.00000  max: 1024.00000  int64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32
[[379 270 431 368]
 [863 540 905 641]
 [312 679 340 707]]
map6_70kx_onzap_CL4100.jpg
Processing 1 images
image                    shape: (1024, 1024, 3)       min:    1.00000  max:  255.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -122.70000  max:  151.10000  float64
image_metas              shape: (1, 14)               min:    0.00000  max: 1024.00000  int64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32
[[534

[[297 487 345 530]
 [518 679 551 728]
 [ 82 125 114 168]
 [135 799 180 845]
 [535 469 560 509]
 [548 114 575 147]
 [401 817 455 879]
 [464  91 509 135]
 [639 400 670 431]
 [617 865 639 897]
 [322 334 356 360]
 [544 755 580 796]
 [685 505 731 549]
 [754 469 795 514]
 [215  88 241 129]
 [140  15 183  68]
 [167 143 195 167]
 [923 697 950 721]]
map1_70kx_onzap_CL4100.jpg
Processing 1 images
image                    shape: (1024, 1024, 3)       min:    0.00000  max:  252.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  148.10000  float64
image_metas              shape: (1, 14)               min:    0.00000  max: 1024.00000  int64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32
[[  42  328   85  366]
 [ 358   57  394  100]
 [ 675  229  711  259]
 [ 556  940  590  979]
 [ 907  728  929  747]
 [ 842  353  888  394]
 [ 977  840 1021  900]
 [ 834  460  849  481]
 [ 528  605  555  648]
 [ 115  793  135  816]


[[509  43 562 108]
 [345 259 372 279]
 [384  65 417  93]
 [247 562 265 587]
 [229 481 244 500]
 [793 935 811 954]
 [ 64 842  89 870]
 [790 730 806 745]
 [323 232 336 247]
 [107 335 136 359]
 [300 105 344 179]]
map5_70kx_onzap_CL4100.jpg
Processing 1 images
image                    shape: (1024, 1024, 3)       min:    0.00000  max:  255.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  151.10000  float64
image_metas              shape: (1, 14)               min:    0.00000  max: 1024.00000  int64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32
[[628 889 685 925]
 [466 888 495 916]
 [184  25 212  54]
 [ 71 727 127 778]
 [122 382 160 413]
 [481 690 505 738]
 [ 22 101  47 132]
 [520 892 540 916]
 [589 231 627 255]
 [ 21 799  65 833]
 [179  96 203 117]
 [307 769 327 785]
 [ 24 649  60 686]
 [ 67 504 107 545]
 [778 530 839 618]
 [ 32 460  64 501]
 [450 485 476 510]
 [315 712 340 737]
 [356 777 373 818]
 [

Re-starting from epoch 10
ROI1_100kx_4200CL_foil1.jpg
Processing 1 images
image                    shape: (1024, 1024, 3)       min:    3.00000  max:  255.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -120.70000  max:  151.10000  float64
image_metas              shape: (1, 14)               min:    0.00000  max: 1024.00000  int64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32
[[ 620  705  645  725]
 [ 467  155  493  182]
 [  72  423   91  438]
 [ 679  923  710  958]
 [ 418  578  443  610]
 [ 215   21  246   49]
 [  84  108  101  128]
 [ 432  464  446  482]
 [ 686 1005  708 1024]
 [ 860  557  901  588]
 [ 887  622  918  654]
 [ 338  823  353  839]
 [ 312  505  328  519]
 [ 368  524  398  561]
 [ 462  237  482  255]
 [ 787   37  804   55]
 [ 379  996  394 1012]
 [ 939  208  964  229]]
map1_70kx.jpg
Processing 1 images
image                    shape: (1024, 1024, 3)       min:    1.00000  max:  254.00000  uint8
mol

[[  42  328   85  366]
 [ 358   57  394  100]
 [ 675  229  711  259]
 [ 556  940  590  979]
 [ 907  728  929  747]
 [ 842  353  888  394]
 [ 977  840 1021  900]
 [ 834  460  849  481]
 [ 528  605  555  648]
 [ 115  793  135  816]
 [ 628   93  668  131]
 [ 287  828  320  861]
 [ 749  999  779 1023]
 [ 802  529  825  547]
 [ 874  111  933  168]
 [  59  755   78  775]
 [ 104  692  138  717]
 [ 341  341  369  369]
 [ 181  803  206  826]
 [ 717  118  740  169]
 [ 921   33  955   76]
 [ 364  179  389  210]
 [ 490  767  519  794]
 [ 540  714  579  760]
 [ 838  546  912  614]
 [  66  685   94  709]
 [ 492   40  555   96]
 [ 490  597  515  632]
 [ 482  139  502  165]
 [  52  530  116  586]
 [ 115  314  150  345]
 [ 436  857  459  883]
 [ 387  875  411  894]
 [ 768  483  786  497]
 [ 314  534  392  611]
 [ 900  892  938  932]
 [ 297  780  311  793]
 [ 421  265  463  309]
 [ 973  153  985  170]
 [ 288  718  324  758]
 [ 539  441  587  486]
 [ 245  990  273 1018]
 [ 215  701  264  743]
 [ 789  781

[[509  43 562 108]
 [345 259 372 279]
 [384  65 417  93]
 [247 562 265 587]
 [229 481 244 500]
 [793 935 811 954]
 [ 64 842  89 870]
 [790 730 806 745]
 [323 232 336 247]
 [107 335 136 359]
 [300 105 344 179]
 [166 642 194 675]
 [151  92 193 128]]
map5_70kx_onzap_CL4100.jpg
Processing 1 images
image                    shape: (1024, 1024, 3)       min:    0.00000  max:  255.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  151.10000  float64
image_metas              shape: (1, 14)               min:    0.00000  max: 1024.00000  int64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32
[[628 889 685 925]
 [466 888 495 916]
 [184  25 212  54]
 [ 71 727 127 778]
 [122 382 160 413]
 [481 690 505 738]
 [ 22 101  47 132]
 [520 892 540 916]
 [589 231 627 255]
 [ 21 799  65 833]
 [179  96 203 117]
 [307 769 327 785]
 [ 24 649  60 686]
 [ 67 504 107 545]
 [778 530 839 618]
 [ 32 460  64 501]
 [450 485 476 510]
 [

[[ 824  660  865  689]
 [ 783  844  818  886]
 [ 165  952  222 1004]
 [ 723  296  761  332]
 [ 585  720  620  764]
 [ 463  853  485  870]
 [ 832   81  875  131]
 [ 497  829  544  849]
 [ 633  757  720  817]
 [ 879  241  904  266]
 [ 638  725  657  741]
 [ 680  324  703  351]
 [ 397  918  453  950]
 [ 904  317  924  340]
 [ 269  577  303  609]
 [ 694  129  729  161]
 [ 393  106  428  126]
 [ 757 1006  790 1024]
 [ 288  258  318  291]
 [ 591  443  617  472]
 [  36  169   53  190]
 [ 411  425  441  444]
 [ 648  988  667 1015]
 [ 654  457  667  474]
 [  12  699   46  734]
 [ 551  651  580  718]
 [ 954  776  987  843]
 [ 368  529  405  566]
 [  22  483   62  519]
 [ 532  866  549  879]
 [ 588   65  618   89]]
#################################################################################
DETECTION_MIN_CONFIDENCE:0.6
Re-starting from epoch 10
ROI1_100kx_4200CL_foil1.jpg
Processing 1 images
image                    shape: (1024, 1024, 3)       min:    3.00000  max:  255.00000  uint8
molded_

[[  22  304   55  358]
 [ 673  831  709  859]
 [ 567  379  601  422]
 [ 786  351  844  396]
 [ 682  561  762  635]
 [ 188  479  230  533]
 [ 104  797  126  819]
 [ 537  345  564  369]
 [  73  522  147  586]
 [ 862   71  884   95]
 [ 184  450  218  484]
 [ 946  507  990  531]
 [ 918  158  956  193]
 [ 590    7  608   34]
 [ 156  718  198  770]
 [ 759  777  780  795]
 [ 436  998  458 1017]
 [ 468  355  517  402]
 [ 141  149  189  211]
 [  27  659   64  692]
 [ 421   90  446  111]
 [ 268  165  312  203]
 [  97  368  121  380]
 [ 980  634 1018  657]
 [ 526  749  550  774]
 [ 163  637  183  652]
 [ 471  617  500  642]
 [ 665  456  689  479]
 [ 960  823  992  858]
 [ 119  891  136  907]
 [  30  604   76  666]
 [  61  455   82  478]
 [ 582  572  595  583]
 [ 344   46  356   61]
 [ 784  760  804  773]
 [ 375  220  419  262]
 [  24  297   40  312]
 [ 741  494  759  508]]
K713_300kx_store4_grid1_0031.jpg
Processing 1 images
image                    shape: (1024, 1024, 3)       min:    5.00000  m

[[635 714 687 763]
 [155 479 192 527]
 [358 697 384 722]
 [788 239 804 261]
 [300 464 332 497]
 [371  27 404  56]
 [756 284 790 307]
 [375 520 396 540]
 [369 212 399 237]
 [785 849 811 876]
 [114 719 149 748]
 [687 545 706 563]
 [ 42 269  71 301]
 [169  86 246 141]
 [516 309 563 349]
 [ 84 830 120 860]
 [328 541 346 558]
 [599 503 629 527]
 [731 592 751 613]
 [912 180 930 201]
 [357 750 383 781]
 [641 449 690 497]
 [908 649 936 673]
 [331 608 348 620]]
ROI3_100kx_4200CL_foil1.jpg
Processing 1 images
image                    shape: (1024, 1024, 3)       min:    0.00000  max:  255.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  151.10000  float64
image_metas              shape: (1, 14)               min:    0.00000  max: 1024.00000  int64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32
[[ 43 466  73 486]
 [467 712 484 734]
 [200 775 225 804]
 [125 291 159 323]
 [171 366 193 385]
 [636 490 665 508]
 

[[810 811 876 879]
 [717 463 776 552]
 [439 735 496 831]
 [195 868 222 907]
 [803  41 830  75]
 [920 880 950 978]
 [901 425 928 447]]
map3_70kx.jpg
Processing 1 images
image                    shape: (1024, 1024, 3)       min:    4.00000  max:  254.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -119.70000  max:  150.10000  float64
image_metas              shape: (1, 14)               min:    0.00000  max: 1024.00000  int64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32
[[910  95 958 189]
 [592 784 610 817]
 [725 160 762 211]
 [562 659 614 717]
 [595 124 646 176]
 [371 478 444 543]
 [310 319 364 409]
 [375 625 400 666]
 [962 759 984 805]
 [616 743 631 764]
 [711  10 735  32]]
map8_70kx_onzap_CL4100.jpg
Processing 1 images
image                    shape: (1024, 1024, 3)       min:    0.00000  max:  253.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  149.10000  float64
image

[[ 781  976  804 1000]
 [ 780  831  809  859]
 [  82  171  102  195]
 [ 120   80  158  126]
 [ 444  939  471  966]
 [ 682  670  699  691]
 [ 663  122  693  143]
 [ 283   95  308  125]
 [ 547  403  583  435]
 [ 304  719  335  735]
 [ 413  497  430  512]
 [ 219  419  237  440]
 [ 735  583  757  606]
 [ 599  770  624  804]
 [ 534  194  555  220]
 [ 856  540  924  628]
 [ 688  738  711  754]
 [   8  293   31  311]
 [ 856  343  871  363]
 [ 411  639  453  682]
 [ 423  617  439  640]
 [ 726  690  768  732]
 [ 270  105  284  118]
 [ 231  309  284  366]
 [ 490  211  521  243]
 [ 401  714  423  729]
 [ 443  581  481  613]
 [ 395  160  418  180]
 [ 684   22  699   38]
 [ 152  876  165  890]
 [ 331  904  352  937]
 [ 912  925  935  951]
 [ 832   54  855   91]
 [ 702  767  719  782]
 [ 662  447  689  460]
 [ 688  277  722  304]
 [ 798  584  829  621]
 [ 810  722  875  783]
 [ 136  659  149  669]
 [ 565  787  586  814]
 [ 239  692  256  705]
 [ 683  559  713  591]
 [ 187   37  215   65]
 [ 404  427

[[  26  746   63  804]
 [ 492  784  518  847]
 [ 208  625  238  652]
 [ 296  479  319  512]
 [ 104  964  137 1002]
 [ 397  334  426  362]
 [ 465  766  487  792]
 [ 343  788  374  812]
 [  53  624   78  666]
 [ 981  179  997  201]
 [ 698  868  739  898]
 [  23  435   46  457]
 [ 334  364  350  384]
 [  93   86  109  102]
 [ 462  573  493  601]
 [ 404  462  428  481]
 [ 296  628  325  661]
 [ 747  594  774  623]
 [ 631  816  669  854]
 [ 409  127  435  146]
 [ 340  844  361  862]
 [ 250  586  268  621]
 [ 105  848  123  867]
 [ 450  537  468  554]
 [ 390  724  433  764]
 [ 194  356  229  374]
 [ 198  286  218  320]
 [ 701  298  730  317]
 [ 536  723  561  759]
 [ 908  894  934  914]
 [ 391  605  451  646]
 [  94  257  127  310]
 [ 806  288  833  331]
 [ 899  500  921  530]
 [ 625  297  649  312]
 [ 748  923  765  940]
 [ 188  153  267  227]
 [ 708  603  719  618]
 [ 934  969  962  988]
 [ 832    6  880   39]
 [ 887   79  921  102]
 [ 646  733  661  752]]
K713_300kx_store4_grid1_0033.jpg


[[509  43 562 108]
 [345 259 372 279]
 [384  65 417  93]
 [247 562 265 587]
 [229 481 244 500]
 [793 935 811 954]
 [ 64 842  89 870]
 [790 730 806 745]
 [323 232 336 247]
 [107 335 136 359]
 [300 105 344 179]
 [166 642 194 675]
 [151  92 193 128]
 [661  64 746 160]
 [835 306 846 322]
 [276 778 327 853]
 [926 501 956 525]
 [287 493 308 515]
 [715 188 741 220]
 [281 199 294 213]
 [418 795 430 808]
 [611  77 623  95]
 [732  35 754  50]
 [711 784 729 802]
 [543 187 558 202]]
map5_70kx_onzap_CL4100.jpg
Processing 1 images
image                    shape: (1024, 1024, 3)       min:    0.00000  max:  255.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  151.10000  float64
image_metas              shape: (1, 14)               min:    0.00000  max: 1024.00000  int64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32
[[628 889 685 925]
 [466 888 495 916]
 [184  25 212  54]
 [ 71 727 127 778]
 [122 382 160 413]
 [

[[207 630 238 683]
 [537 789 581 845]
 [934 884 952 912]
 [433 869 467 928]
 [891 272 929 341]
 [643 349 673 379]
 [149 227 194 294]
 [643 578 677 609]
 [466 724 492 767]
 [258  58 277  86]
 [942 671 989 708]]
map4_70kx.jpg
Processing 1 images
image                    shape: (1024, 1024, 3)       min:    0.00000  max:  252.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  148.10000  float64
image_metas              shape: (1, 14)               min:    0.00000  max: 1024.00000  int64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32
[[ 379  270  431  368]
 [ 863  540  905  641]
 [ 312  679  340  707]
 [ 557  178  591  248]
 [ 676  660  700  693]
 [ 107  179  122  203]
 [ 355  993  390 1023]
 [ 362  760  383  784]
 [ 742   19  765   49]
 [ 672  438  694  467]
 [  21  767   38  791]
 [ 480  103  503  129]]
map6_70kx_onzap_CL4100.jpg
Processing 1 images
image                    shape: (1024, 1024, 3)     

[[439 896 470 923]
 [547 699 609 764]
 [642 660 711 717]
 [199 455 241 485]
 [525 516 583 564]
 [692 766 741 808]
 [801 600 848 629]
 [210 515 250 557]
 [ 99 551 152 606]
 [ 34 780  60 809]
 [560  88 611 137]
 [673  40 701  67]
 [932 605 970 637]
 [855 949 912 998]
 [164 848 183 867]
 [958   9 999  46]
 [815 736 852 765]
 [375 948 397 964]
 [  8 675  60 728]
 [730 732 749 751]
 [610 538 639 557]
 [399 973 419 996]
 [458  83 499 120]
 [234 402 263 439]
 [513 761 528 776]
 [390 682 415 706]
 [149  74 180 110]
 [759 906 784 925]
 [589 791 604 808]
 [536 425 567 454]
 [318 958 333 988]
 [290 530 312 550]
 [740 432 764 451]
 [427 194 493 236]
 [582 396 619 434]
 [201 368 228 403]
 [782 976 815 998]
 [458 689 500 722]
 [306 140 323 158]
 [674 822 688 835]
 [963 654 988 676]
 [788 814 809 829]
 [679 935 752 965]
 [738 827 771 848]
 [326  39 354  61]
 [125 922 143 942]
 [520 934 542 953]
 [681 266 726 297]
 [470 590 521 617]
 [412 691 497 855]]
ROI15_100kx_4200CL_foil1.jpg
Processing 1 images


[[ 57 366 107 433]
 [659 236 718 307]
 [913 252 957 293]
 [523 279 552 309]
 [734 775 802 837]
 [136 908 194 969]
 [339 811 419 907]
 [633 363 694 431]
 [546 682 588 736]
 [206 722 240 777]
 [768 654 806 693]
 [706 499 741 543]
 [827 647 867 698]
 [509 337 551 386]
 [127 120 151 158]
 [522 663 548 693]
 [597 613 636 661]
 [491 246 520 269]
 [286 933 314 973]
 [694 603 723 637]
 [489 599 526 629]
 [227 830 253 853]
 [744 446 778 478]
 [ 94 680 117 704]
 [294 410 334 441]
 [ 94 297 125 345]
 [774 304 797 338]]
ROI2_100kx_4200CL_foil1.jpg
Processing 1 images
image                    shape: (1024, 1024, 3)       min:    4.00000  max:  255.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -119.70000  max:  151.10000  float64
image_metas              shape: (1, 14)               min:    0.00000  max: 1024.00000  int64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32
[[783 543 814 590]
 [262 417 288 435]
 [221 542 236 558]
 

[[ 202  506  223  543]
 [ 112  710  131  731]
 [ 147  755  164  786]
 [ 237  391  270  437]
 [ 116  145  154  200]
 [ 658  197  690  239]
 [ 248  110  270  137]
 [ 626  400  649  437]
 [ 664  329  699  377]
 [ 541  702  559  722]
 [ 554  761  585  780]
 [ 413  934  428  958]
 [ 114  108  135  132]
 [ 689   72  701   98]
 [ 524  354  540  381]
 [ 225  942  254  986]
 [ 281  125  304  146]
 [ 464    7  495   37]
 [ 163   58  179   78]
 [ 298  589  330  613]
 [ 285  327  323  354]
 [ 173  444  199  477]
 [  58  672   79  697]
 [  93  335  188  410]
 [ 587  840  610  861]
 [ 628  265  646  292]
 [ 925  728  959  776]
 [ 466  968  511  992]
 [ 496   96  519  135]
 [ 952   18  974   47]
 [ 199   97  229  117]
 [  28  619   65  667]
 [   5  803   71  903]
 [ 208  132  222  161]
 [ 410  231  424  250]
 [ 556  366  595  410]
 [ 519  400  534  421]
 [ 477  204  509  229]
 [ 129   39  143   66]
 [ 304   70  318   89]
 [ 104  493  148  547]
 [ 344  692  368  706]
 [ 371  475  386  491]
 [ 941  295

[[ 824  660  865  689]
 [ 783  844  818  886]
 [ 165  952  222 1004]
 [ 723  296  761  332]
 [ 585  720  620  764]
 [ 463  853  485  870]
 [ 832   81  875  131]
 [ 497  829  544  849]
 [ 633  757  720  817]
 [ 879  241  904  266]
 [ 638  725  657  741]
 [ 680  324  703  351]
 [ 397  918  453  950]
 [ 904  317  924  340]
 [ 269  577  303  609]
 [ 694  129  729  161]
 [ 393  106  428  126]
 [ 757 1006  790 1024]
 [ 288  258  318  291]
 [ 591  443  617  472]
 [  36  169   53  190]
 [ 411  425  441  444]
 [ 648  988  667 1015]
 [ 654  457  667  474]
 [  12  699   46  734]
 [ 551  651  580  718]
 [ 954  776  987  843]
 [ 368  529  405  566]
 [  22  483   62  519]
 [ 532  866  549  879]
 [ 588   65  618   89]
 [  38  341   78  368]
 [ 282   55  300   74]
 [ 185  409  226  433]
 [ 539  172  575  201]
 [ 790   49  851   87]
 [ 478  760  529  792]
 [ 763  812  782  836]
 [ 279  825  327  874]
 [ 393  164  413  179]
 [  75  420  101  450]
 [ 753  307  781  342]
 [ 400  222  432  253]
 [ 876  981

[[ 660  908  732  970]
 [ 425  921  444  941]
 [ 713  290  741  313]
 [ 520  758  536  782]
 [ 243  224  265  245]
 [ 571  718  591  746]
 [ 955   83  986  130]
 [ 506  939  530  972]
 [  86  671  109  686]
 [ 551  289  568  309]
 [ 228   82  275  133]
 [  25  861   53  885]
 [ 847  211  862  233]
 [ 607  702  630  718]
 [ 105  795  123  813]
 [ 783   96  799  111]
 [ 994  753 1022  785]
 [ 367  144  417  217]
 [  92  495  157  559]
 [  63  897   78  915]
 [ 336  733  392  791]
 [  60  430   78  450]
 [ 769   54  779   67]
 [ 235  289  290  340]
 [ 365  441  381  478]
 [ 921  636  950  654]]
map9_70kx_onzap_CL4100.jpg
Processing 1 images
image                    shape: (1024, 1024, 3)       min:    0.00000  max:  254.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  150.10000  float64
image_metas              shape: (1, 14)               min:    0.00000  max: 1024.00000  int64
anchors                  shape: (1, 261888, 4)        min:   -0.35390 

[[ 501  301  526  343]
 [ 869  270  890  291]
 [ 566  198  581  224]
 [   3  580   29  617]
 [ 796  253  824  279]
 [ 391  110  442  173]
 [ 101  451  122  480]
 [ 606  229  633  250]
 [ 752  892  771  910]
 [ 119  918  137  936]
 [ 326  838  344  856]
 [ 872  225  894  252]
 [ 905  431  947  464]
 [ 613  336  634  353]
 [ 388  254  401  269]
 [ 728  314  789  401]
 [ 248  339  268  363]
 [ 252   42  303   82]
 [ 668  739  680  758]
 [ 468  697  482  711]
 [ 214  708  231  728]
 [ 454  272  468  289]
 [ 495  793  511  809]
 [ 304  744  325  757]
 [ 744  744  769  770]
 [ 541   14  558   40]
 [ 280   79  350  148]
 [ 420  241  447  266]
 [ 296  927  332  967]
 [ 539  380  562  402]
 [ 599  529  624  552]
 [ 632    0  672   36]
 [ 339  152  356  169]
 [ 481  515  501  529]
 [ 454  442  498  460]
 [ 422  729  433  750]
 [1007  211 1024  238]]
ROI10_100kx_4200CL_foil1.jpg
Processing 1 images
image                    shape: (1024, 1024, 3)       min:    0.00000  max:  255.00000  uint8
molde

[[ 803  872  846  916]
 [ 604  175  631  195]
 [ 517  102  547  129]
 [ 614  546  641  576]
 [ 899  778  922  796]
 [ 653  246  680  270]
 [ 206  251  229  272]
 [ 654  199  676  222]
 [ 973  367  990  386]
 [  30  735   61  761]
 [  45   95   72  119]
 [ 685   49  710   74]
 [ 961  770  993  831]
 [ 377  551  397  591]
 [ 778  558  803  579]
 [ 666  468  700  495]
 [ 848 1001  870 1020]
 [ 339  344  378  382]
 [ 545  980  559  996]
 [ 782  842  802  860]
 [ 311  336  349  383]
 [ 382  574  398  594]
 [ 883  245  896  259]
 [ 923  737  935  751]
 [ 472  914  492  932]
 [ 249  522  263  534]
 [ 227  900  252  925]
 [ 638  317  673  347]
 [ 496  437  510  450]]
ROI13_100kx_4200CL_foil1.jpg
Processing 1 images
image                    shape: (1024, 1024, 3)       min:    0.00000  max:  255.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  151.10000  float64
image_metas              shape: (1, 14)               min:    0.00000  max: 1024.00000  int64

Re-starting from epoch 10
ROI1_100kx_4200CL_foil1.jpg
Processing 1 images
image                    shape: (1024, 1024, 3)       min:    3.00000  max:  255.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -120.70000  max:  151.10000  float64
image_metas              shape: (1, 14)               min:    0.00000  max: 1024.00000  int64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32
[[ 620  705  645  725]
 [ 467  155  493  182]
 [  72  423   91  438]
 [ 679  923  710  958]
 [ 418  578  443  610]
 [ 215   21  246   49]
 [  84  108  101  128]
 [ 432  464  446  482]
 [ 686 1005  708 1024]
 [ 860  557  901  588]
 [ 887  622  918  654]
 [ 338  823  353  839]
 [ 312  505  328  519]
 [ 368  524  398  561]
 [ 462  237  482  255]
 [ 787   37  804   55]
 [ 379  996  394 1012]
 [ 939  208  964  229]
 [ 155   95  172  118]
 [ 744  566  763  594]
 [  36  449   46  462]
 [ 216   76  259  136]
 [ 988  642 1003  657]]
map1_70kx.jpg
Pr

[[  22  304   55  358]
 [ 673  831  709  859]
 [ 567  379  601  422]
 [ 786  351  844  396]
 [ 682  561  762  635]
 [ 188  479  230  533]
 [ 104  797  126  819]
 [ 537  345  564  369]
 [  73  522  147  586]
 [ 862   71  884   95]
 [ 184  450  218  484]
 [ 946  507  990  531]
 [ 918  158  956  193]
 [ 590    7  608   34]
 [ 156  718  198  770]
 [ 759  777  780  795]
 [ 436  998  458 1017]
 [ 468  355  517  402]
 [ 141  149  189  211]
 [  27  659   64  692]
 [ 421   90  446  111]
 [ 268  165  312  203]
 [  97  368  121  380]
 [ 980  634 1018  657]
 [ 526  749  550  774]
 [ 163  637  183  652]
 [ 471  617  500  642]
 [ 665  456  689  479]
 [ 960  823  992  858]
 [ 119  891  136  907]
 [  30  604   76  666]
 [  61  455   82  478]
 [ 582  572  595  583]
 [ 344   46  356   61]
 [ 784  760  804  773]
 [ 375  220  419  262]
 [  24  297   40  312]
 [ 741  494  759  508]
 [ 276  429  339  482]
 [  92  398  117  421]]
K713_300kx_store4_grid1_0031.jpg
Processing 1 images
image                    s

[[ 453  109  472  127]
 [ 358  285  397  350]
 [ 773   93  791  121]
 [ 521  874  554  911]
 [ 100  704  128  740]
 [ 416  424  464  465]
 [ 568  674  616  722]
 [ 399  145  412  167]
 [ 395   39  411   63]
 [ 821   61  856  111]
 [ 451   39  480   56]
 [ 114  616  159  642]
 [ 592  258  623  299]
 [ 945  462  989  528]
 [ 423  769  470  815]
 [ 371  624  403  655]
 [ 567  978  599 1016]
 [  26  248   40  265]
 [   1  724   32  771]
 [  69  219   92  240]
 [ 624  719  659  743]
 [ 262  619  275  637]
 [ 149  536  168  559]
 [ 829  117  885  158]
 [ 462  299  485  336]
 [ 456  550  479  572]
 [ 121  295  197  371]
 [ 386  465  407  484]
 [ 670  745  704  773]
 [ 312  100  352  132]
 [ 650  296  686  333]
 [ 672  637  736  698]
 [ 318  843  347  861]
 [ 811  882  825  905]
 [ 234  996  247 1014]]
map7_70kx_onzap_CL4100.jpg
Processing 1 images
image                    shape: (1024, 1024, 3)       min:    0.00000  max:  255.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)   

[[ 377   75  400  110]
 [ 775  963  796  987]
 [ 803  527  821  553]
 [ 256  754  273  775]
 [  98  221  122  249]
 [ 413   67  431   96]
 [ 449  189  467  213]
 [ 343  906  369  941]
 [ 585  469  607  523]
 [ 514  107  535  145]
 [ 216  785  229  799]
 [ 612  168  627  194]
 [  69    8  103   61]
 [  55  179   70  194]
 [ 888  474  931  493]
 [ 309  206  319  224]
 [ 540  758  558  776]
 [ 409  350  435  387]
 [ 201  254  223  277]
 [ 289  626  314  664]
 [ 843  730  864  749]
 [  92  874  114  901]
 [ 749  372  771  389]
 [ 173  494  203  509]
 [ 385  708  401  725]
 [ 970  829 1011  852]
 [ 271  115  294  139]
 [ 255  996  276 1016]
 [ 771  132  802  164]
 [ 768  511  785  531]
 [ 778  413  790  428]
 [ 373  619  403  653]
 [ 456  678  489  704]
 [ 728  649  750  664]
 [ 311  400  348  460]
 [ 311  822  339  844]
 [ 190   30  224   60]
 [ 496  174  527  194]
 [ 368  576  396  595]
 [ 138  792  168  837]
 [ 733  726  766  755]
 [ 250  311  274  343]
 [ 593  610  607  623]
 [ 214  130

[[243 884 275 928]
 [379 538 398 561]
 [755 853 785 917]
 [981 414 999 438]
 [599 394 621 426]
 [838 474 856 501]
 [961 770 977 809]
 [413 230 437 262]
 [869 604 899 637]]
ROI12_100kx_4200CL_foil1.jpg
Processing 1 images
image                    shape: (1024, 1024, 3)       min:    0.00000  max:  254.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  150.10000  float64
image_metas              shape: (1, 14)               min:    0.00000  max: 1024.00000  int64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32
[[  61  657  100  685]
 [ 430  114  453  133]
 [ 127   98  138  121]
 [  18  440   31  467]
 [ 660  849  679  870]
 [ 177  397  189  413]
 [ 837  561  867  592]
 [ 272  652  338  726]
 [  69  457  117  492]
 [ 690  993  750 1023]
 [ 175  863  195  876]
 [ 406  502  430  530]
 [ 241  685  259  702]
 [ 478  534  499  558]
 [ 615  134  634  159]
 [ 436  150  466  195]
 [ 153  963  179 1008]
 [ 326  

[[ 297  487  345  530]
 [ 518  679  551  728]
 [  82  125  114  168]
 [ 135  799  180  845]
 [ 535  469  560  509]
 [ 548  114  575  147]
 [ 401  817  455  879]
 [ 464   91  509  135]
 [ 639  400  670  431]
 [ 617  865  639  897]
 [ 322  334  356  360]
 [ 544  755  580  796]
 [ 685  505  731  549]
 [ 754  469  795  514]
 [ 215   88  241  129]
 [ 140   15  183   68]
 [ 167  143  195  167]
 [ 923  697  950  721]
 [ 935  583  974  621]
 [ 640  984  691 1014]
 [ 539  585  560  637]
 [ 413  231  440  260]
 [ 672  117  716  164]
 [ 233  485  256  514]
 [ 363   18  392   43]
 [ 234  873  265  900]
 [   7  689   39  736]
 [ 857  667  883  685]]
map1_70kx_onzap_CL4100.jpg
Processing 1 images
image                    shape: (1024, 1024, 3)       min:    0.00000  max:  252.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  148.10000  float64
image_metas              shape: (1, 14)               min:    0.00000  max: 1024.00000  int64
anchors                 

[[ 635  714  687  763]
 [ 155  479  192  527]
 [ 358  697  384  722]
 [ 788  239  804  261]
 [ 300  464  332  497]
 [ 371   27  404   56]
 [ 756  284  790  307]
 [ 375  520  396  540]
 [ 369  212  399  237]
 [ 785  849  811  876]
 [ 114  719  149  748]
 [ 687  545  706  563]
 [  42  269   71  301]
 [ 169   86  246  141]
 [ 516  309  563  349]
 [  84  830  120  860]
 [ 328  541  346  558]
 [ 599  503  629  527]
 [ 731  592  751  613]
 [ 912  180  930  201]
 [ 357  750  383  781]
 [ 641  449  690  497]
 [ 908  649  936  673]
 [ 331  608  348  620]
 [ 224  155  274  202]
 [ 970  323 1024  366]
 [ 159  972  181  987]]
ROI3_100kx_4200CL_foil1.jpg
Processing 1 images
image                    shape: (1024, 1024, 3)       min:    0.00000  max:  255.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  151.10000  float64
image_metas              shape: (1, 14)               min:    0.00000  max: 1024.00000  int64
anchors                  shape: (1, 261888, 4)

[[810 811 876 879]
 [717 463 776 552]
 [439 735 496 831]
 [195 868 222 907]
 [803  41 830  75]
 [920 880 950 978]
 [901 425 928 447]]
map3_70kx.jpg
Processing 1 images
image                    shape: (1024, 1024, 3)       min:    4.00000  max:  254.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -119.70000  max:  150.10000  float64
image_metas              shape: (1, 14)               min:    0.00000  max: 1024.00000  int64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32
[[910  95 958 189]
 [592 784 610 817]
 [725 160 762 211]
 [562 659 614 717]
 [595 124 646 176]
 [371 478 444 543]
 [310 319 364 409]
 [375 625 400 666]
 [962 759 984 805]
 [616 743 631 764]
 [711  10 735  32]
 [121  45 173  93]
 [209 403 225 421]]
map8_70kx_onzap_CL4100.jpg
Processing 1 images
image                    shape: (1024, 1024, 3)       min:    0.00000  max:  253.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123

In [7]:
def parseBoundingBoxesSingleType(filename):
    with open(filename) as f:
        contents = {}
        num = 1
        for line in f:
            contents[num] = line.strip().split()
            num+=1
            
        for length in range(len(contents)):
            for length2 in range(len(contents[length+1])):
                contents[length+1][length2] = int(float(contents[length+1][length2]))
    return contents

In [8]:
def computeAverage(listname):

    total = 0
    total2 = 0
    for i in range(len(listname)):
        total += listname[i][0]
        total2 += listname[i][1]
    return round(total/total2, 2)

In [9]:
def calculateRecallSingleType(originalList, generatedList):
    labelCount = 0
    denominator = 0
    
    denominator = len(originalList)
                   
    for iterate in range(1, len(generatedList) + 1):
        for iterate2 in range(1, len(originalList) + 1):
            if(generatedList[iterate][0] - 20 <= originalList[iterate2][0] <= generatedList[iterate][0] + 20 and
                    generatedList[iterate][1] - 20 <= originalList[iterate2][1] <= generatedList[iterate][1] + 20 and
                    generatedList[iterate][2] - 20 <= originalList[iterate2][2] <= generatedList[iterate][2] + 20 and 
                    generatedList[iterate][3] - 20 <= originalList[iterate2][3] <= generatedList[iterate][3] + 20) :
                        labelCount += 1
    
    return labelCount,denominator

In [10]:
def calculatePrecisionSingleType(originalList, generatedList):
    labelCount = 0
    denominator = 0
    
    denominator = len(generatedList)
        
    for iterate in range(1, len(generatedList) + 1):
        for iterate2 in range(1, len(originalList) + 1):
            if(generatedList[iterate][0] - 20 <= originalList[iterate2][0] <= generatedList[iterate][0] + 20 and
                    generatedList[iterate][1] - 20 <= originalList[iterate2][1] <= generatedList[iterate][1] + 20 and
                    generatedList[iterate][2] - 20 <= originalList[iterate2][2] <= generatedList[iterate][2] + 20 and 
                    generatedList[iterate][3] - 20 <= originalList[iterate2][3] <= generatedList[iterate][3] + 20) :
                        labelCount += 1
    
    return labelCount,denominator
    

In [23]:
F1list ={}
for n in range(9, 0, -1):
    print('#################################################################################')
    print('DETECTION_MIN_CONFIDENCE'+ ':' + str(n/10))
    def F1_Score(presicion, recall):
        p = 1/presicion
        r = 1/recall
        F1Score = 2/( p + r )
        return F1Score

    def calculate():
        with open("/srv/home/whao/NextGen/new_debug/run/run1/datasets/dataprep/datasets/Loop_detection/testimages.txt") as f:
            preclist = []
            reclist = []
            for line in f:

                try:
                    origlist = parseBoundingBoxesSingleType('/srv/home/whao/NextGen/new_debug/run/run3/samples/original/' + line[:-5] + '.txt')

                    genlist = parseBoundingBoxesSingleType('/srv/home/whao/NextGen/new_debug/run/run1/samples/generated' + str(n) + '/' + line[:-5] + '.txt')
                    preclist.append(calculatePrecisionSingleType(origlist, genlist))
                    reclist.append(calculateRecallSingleType(origlist, genlist))
                except:
                    print(line[:-5] + '.txt')

            return reclist, preclist
    
    recalllist, precisionlist = calculate()
    recall = computeAverage(recalllist)
    precision = computeAverage(precisionlist)
    F1_Score = F1_Score(precision,recall)
    print('recall:',recall,'precision:',precision,'F1_Score:',F1_Score)
    F1list[str(n)] = (F1_Score)
    

#################################################################################
DETECTION_MIN_CONFIDENCE:0.9
map9_70kx_onzap_CL410.txt
recall: 0.22 precision: 0.89 F1_Score: 0.35279279279279274
#################################################################################
DETECTION_MIN_CONFIDENCE:0.8
map9_70kx_onzap_CL410.txt
recall: 0.36 precision: 0.84 F1_Score: 0.504
#################################################################################
DETECTION_MIN_CONFIDENCE:0.7
map9_70kx_onzap_CL410.txt
recall: 0.45 precision: 0.82 F1_Score: 0.5811023622047243
#################################################################################
DETECTION_MIN_CONFIDENCE:0.6
map9_70kx_onzap_CL410.txt
recall: 0.53 precision: 0.8 F1_Score: 0.637593984962406
#################################################################################
DETECTION_MIN_CONFIDENCE:0.5
map9_70kx_onzap_CL410.txt
recall: 0.59 precision: 0.77 F1_Score: 0.6680882352941176
#######################################

In [32]:
print('DETECTION_MIN_CONFIDENCE with the largest F1:')
int(max(F1list.items(), key=operator.itemgetter(1))[0])/10

DETECTION_MIN_CONFIDENCE with the largest F1:


0.5